my_dict = {
  'a00': 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
  'a01': 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
  'a02': 'XXXXXXXXXXXXXXXX   XXXXXXXXXXXXXXXX',
  'a03': 'XXXXXXXXXXXXXXX     XXXXXXXXXXXXXXX',
  'a04': 'XXXXXXXXXXXXXX       XXXXXXXXXXXXXX',
  'a05': 'XXXXXXXXXXXXX         XXXXXXXXXXXXX',
  'a06': 'XXXXXXXXXXXX           XXXXXXXXXXXX',
  'a07': 'XXXXXXXXXXX             XXXXXXXXXXX',
  'a08': 'XXXXXXXXXX       X       XXXXXXXXXX',
  'a09': 'XXXXXXXXX       XXX       XXXXXXXXX',
  'a10': 'XXXXXXXX       XXXXX       XXXXXXXX',
  'a11': 'XXXXXXX                     XXXXXXX',
  'a12': 'XXXXXX                       XXXXXX',
  'a13': 'XXXXX                         XXXXX',
  'a14': 'XXXX       XXXXXXXXXXXXX       XXXX',
  'a15': 'XXX       XXXXXXXXXXXXXXX       XXX',
  'a16': 'XX       XXXXXXXXXXXXXXXXX       XX',
  'a17': 'X       XXXXXXXXXXXXXXXXXXX       X',
  'a18': 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
  'a19': 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
  'b00': 'XXXXXXXXXXXXXXXXXXXXXX',
  'b01': 'XXXXXXXXXXXXXXXXXXXXXX',
  'b02': 'X                 XXXX',
  'b03': 'X                  XXX',
  'b04': 'X                   XX',
  'b05': 'X        XXXXX       X',
  'b06': 'XXX      XXXXX       X',
  'b07': 'XXX      XXXXX       X',
  'b08': 'XXX                 XX',
  'b09': 'XXX                XXX',
  'b10': 'XXX                 XX',
  'b11': 'XXX      XXXXX       X',
  'b12': 'XXX      XXXXX       X',
  'b13': 'XXX      XXXXX       X',
  'b14': 'X                    X',
  'b15': 'X                   XX',
  'b16': 'X                  XXX',
  'b17': 'X                 XXXX',
  'b18': 'XXXXXXXXXXXXXXXXXXXXXX',
  'b19': 'XXXXXXXXXXXXXXXXXXXXXX',
  'c00': 'XXXXXXXXXXXXXXXXXXXXXXX',
  'c01': 'XXXXXXXXXXXXXXXXXXXXXXX',
  'c02': 'XXXXXXXXX             X',
  'c03': 'XXXXXX                X',
  'c04': 'XXXX                  X',
  'c05': 'XXX                   X',
  'c06': 'XX       XXXXXXX      X',
  'c07': 'X       XXXXXXXXXXXXXXX',
  'c08': 'X       XXXXXXXXXXXXXXX',
  'c09': 'X       XXXXXXXXXXXXXXX',
  'c10': 'X       XXXXXXXXXXXXXXX',
  'c11': 'X       XXXXXXXXXXXXXXX',
  'c12': 'X       XXXXXXXXXXXXXXX',
  'c13': 'XX       XXXXXXX      X',
  'c14': 'XXX                   X',
  'c15': 'XXXX                  X',
  'c16': 'XXXXXX                X',
  'c17': 'XXXXXXXXX             X',
  'c18': 'XXXXXXXXXXXXXXXXXXXXXXX',
  'c19': 'XXXXXXXXXXXXXXXXXXXXXXX',
  'd00': 'XXXXXXXXXXXXXXXXXXXXXXX',
  'd01': 'XXXXXXXXXXXXXXXXXXXXXXX',
  'd02': 'X             XXXXXXXXX',
  'd03': 'X                XXXXXX',
  'd04': 'X                  XXXX',
  'd05': 'X                   XXX',
  'd06': 'XXX       XXXX       XX',
  'd07': 'XXX       XXXXX       X',
  'd08': 'XXX       XXXXX       X',
  'd09': 'XXX       XXXXX       X',
  'd10': 'XXX       XXXXX       X',
  'd11': 'XXX       XXXXX       X',
  'd12': 'XXX       XXXXX       X',
  'd13': 'XXX       XXXX       XX',
  'd14': 'X                   XXX',
  'd15': 'X                  XXXX',
  'd16': 'X                XXXXXX',
  'd17': 'X             XXXXXXXXX',
  'd18': 'XXXXXXXXXXXXXXXXXXXXXXX',
  'd19': 'XXXXXXXXXXXXXXXXXXXXXXX',
  'e00': 'XXXXXXXXXXXXXXXXXXXXXXXX',
  'e01': 'XXXXXXXXXXXXXXXXXXXXXXXX',
  'e02': 'X                      X',
  'e03': 'X                      X',
  'e04': 'X                      X',
  'e05': 'X                      X',
  'e06': 'XXX       XXXXXXX      X',
  'e07': 'XXX       XXXXXXXXXXXXXX',
  'e08': 'XXX                 XXXX',
  'e09': 'XXX                 XXXX',
  'e10': 'XXX                 XXXX',
  'e11': 'XXX                 XXXX',
  'e12': 'XXX       XXXXXXXXXXXXXX',
  'e13': 'XXX       XXXXXXX      X',
  'e14': 'X                      X',
  'e15': 'X                      X',
  'e16': 'X                      X',
  'e17': 'X                      X',
  'e18': 'XXXXXXXXXXXXXXXXXXXXXXXX',
  'e19': 'XXXXXXXXXXXXXXXXXXXXXXXX',
  'f00': 'XXXXXXXXXXXXXXXXXXXXXXXX',
  'f01': 'XXXXXXXXXXXXXXXXXXXXXXXX',
  'f02': 'X                      X',
  'f03': 'X                      X',
  'f04': 'X                      X',
  'f05': 'X                      X',
  'f06': 'XXX       XXXXXXX      X',
  'f07': 'XXX       XXXXXXXXXXXXXX',
  'f08': 'XXX                 XXXX',
  'f09': 'XXX                 XXXX',
  'f10': 'XXX                 XXXX',
  'f11': 'XXX                 XXXX',
  'f12': 'XXX       XXXXXXXXXXXXXX',
  'f13': 'XXX       XXXXXXXXXXXXXX',
  'f14': 'X           XXXXXXXXXXXX',
  'f15': 'X           XXXXXXXXXXXX',
  'f16': 'X           XXXXXXXXXXXX',
  'f17': 'X           XXXXXXXXXXXX',
  'f18': 'XXXXXXXXXXXXXXXXXXXXXXXX',
  'f19': 'XXXXXXXXXXXXXXXXXXXXXXXX',
  'g00': 'XXXXXXXXXXXXXXXXXXXXXXX',
  'g01': 'XXXXXXXXXXXXXXXXXXXXXXX',
  'g02': 'XXXXXXXXX             X',
  'g03': 'XXXXXX                X',
  'g04': 'XXXX                  X',
  'g05': 'XXX                   X',
  'g06': 'XX       XXXXXXX      X',
  'g07': 'X       XXXXXXXXXXXXXXX',
  'g08': 'X       XXXXXXXXXXXXXXX',
  'g09': 'X       XXXX          X',
  'g10': 'X       XXXX          X',
  'g11': 'X       XXXX          X',
  'g12': 'X       XXXXXXXX      X',
  'g13': 'XX       XXXXXXX      X',
  'g14': 'XXX                   X',
  'g15': 'XXXX                  X',
  'g16': 'XXXXXX                X',
  'g17': 'XXXXXXXXX      XXX    X',
  'g18': 'XXXXXXXXXXXXXXXXXXXXXXX',
  'g19': 'XXXXXXXXXXXXXXXXXXXXXXX',
  'h00': 'XXXXXXXXXXXXXXXXXXXXXXXXX',
  'h01': 'XXXXXXXXXXXXXXXXXXXXXXXXX',
  'h02': 'X         XXXXX         X',
  'h03': 'X         XXXXX         X',
  'h04': 'X         XXXXX         X',
  'h05': 'X         XXXXX         X',
  'h06': 'XXX       XXXXX       XXX',
  'h07': 'XXX       XXXXX       XXX',
  'h08': 'XXX                   XXX',
  'h09': 'XXX                   XXX',
  'h10': 'XXX                   XXX',
  'h11': 'XXX                   XXX',
  'h12': 'XXX       XXXXX       XXX',
  'h13': 'XXX       XXXXX       XXX',
  'h14': 'X         XXXXX         X',
  'h15': 'X         XXXXX         X',
  'h16': 'X         XXXXX         X',
  'h17': 'X         XXXXX         X',
  'h18': 'XXXXXXXXXXXXXXXXXXXXXXXXX',
  'h19': 'XXXXXXXXXXXXXXXXXXXXXXXXX',
  'i00': 'XXXXXXXXXXXX',
  'i01': 'XXXXXXXXXXXX',
  'i02': 'X          X',
  'i03': 'X          X',
  'i04': 'X          X',
  'i05': 'X          X',
  'i06': 'XXX      XXX',
  'i07': 'XXX      XXX',
  'i08': 'XXX      XXX',
  'i09': 'XXX      XXX',
  'i10': 'XXX      XXX',
  'i11': 'XXX      XXX',
  'i12': 'XXX      XXX',
  'i13': 'XXX      XXX',
  'i14': 'X          X',
  'i15': 'X          X',
  'i16': 'X          X',
  'i17': 'X          X',
  'i18': 'XXXXXXXXXXXX',
  'i19': 'XXXXXXXXXXXX',
  'j00': 'XXXXXXXXXXXXXXXXXXXXXXX',
  'j01': 'XXXXXXXXXXXXXXXXXXXXXXX',
  'j02': 'XXXXXXXXXXX           X',
  'j03': 'XXXXXXXXXXX           X',
  'j04': 'XXXXXXXXXXX           X',
  'j05': 'XXXXXXXXXXX           X',
  'j06': 'XXXXXXXXXXXXX       XXX',
  'j07': 'XXXXXXXXXXXXX       XXX',
  'j08': 'XXXXXXXXXXXXX       XXX',
  'j09': 'XXXXXXXXXXXXX       XXX',
  'j10': 'XXXXXXXXXXXXX       XXX',
  'j11': 'X       XXXXX       XXX',
  'j12': 'X       XXXXX       XXX',
  'j13': 'X        XXX        XXX',
  'j14': 'X                   XXX',
  'j15': 'XX                 XXXX',
  'j16': 'XXXX             XXXXXX',
  'j17': 'XXXXXX         XXXXXXXX',
  'j18': 'XXXXXXXXXXXXXXXXXXXXXXX',
  'j19': 'XXXXXXXXXXXXXXXXXXXXXXX',
  'k00': 'XXXXXXXXXXXXXXXXXXXXXX',
  'k01': 'XXXXXXXXXXXXXXXXXXXXXX',
  'k02': 'X         XXXX       X',
  'k03': 'X         XXXX       X',
  'k04': 'X         XXXX       X',
  'k05': 'X         XXX        X',
  'k06': 'X         XX         X',
  'k07': 'XXX       X       XXXX',
  'k08': 'XXX              XXXXX',
  'k09': 'XXX             XXXXXX',
  'k10': 'XXX             XXXXXX',
  'k11': 'XXX              XXXXX',
  'k12': 'XXX       X       XXXX',
  'k13': 'X         XX         X',
  'k14': 'X         XXX        X',
  'k15': 'X         XXXX       X',
  'k16': 'X         XXXX       X',
  'k17': 'X         XXXX       X',
  'k18': 'XXXXXXXXXXXXXXXXXXXXXX',
  'k19': 'XXXXXXXXXXXXXXXXXXXXXX',
  'l00': 'XXXXXXXXXXXXXXXXXXXXXXXX',
  'l01': 'XXXXXXXXXXXXXXXXXXXXXXXX',
  'l02': 'X           XXXXXXXXXXXX',
  'l03': 'X           XXXXXXXXXXXX',
  'l04': 'X           XXXXXXXXXXXX',
  'l05': 'X           XXXXXXXXXXXX',
  'l06': 'XXX       XXXXXXXXXXXXXX',
  'l07': 'XXX       XXXXXXXXXXXXXX',
  'l08': 'XXX       XXXXXXXXXXXXXX',
  'l09': 'XXX       XXXXXXXXXXXXXX',
  'l10': 'XXX       XXXXXXXXXXXXXX',
  'l11': 'XXX       XXXXXXXXXXXXXX',
  'l12': 'XXX       XXXXXXXXXXXXXX',
  'l13': 'XXX       XXXXXXX      X',
  'l14': 'X                      X',
  'l15': 'X                      X',
  'l16': 'X                      X',
  'l17': 'X                      X',
  'l18': 'XXXXXXXXXXXXXXXXXXXXXXXX',
  'l19': 'XXXXXXXXXXXXXXXXXXXXXXXX',
  'm00': 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
  'm01': 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
  'm02': 'X        XXXXXXXXXXXXXXX        X',
  'm03': 'X         XXXXXXXXXXXXX         X',
  'm04': 'X          XXXXXXXXXXX          X',
  'm05': 'X           XXXXXXXXX           X',
  'm06': 'X            XXXXXXX            X',
  'm07': 'X             XXXXX             X',
  'm08': 'X              XXX              X',
  'm09': 'X        X      X      X        X',
  'm10': 'X        XX           XX        X',
  'm11': 'X        XXX         XXX        X',
  'm12': 'X        XXXX       XXXX        X',
  'm13': 'X        XXXXX     XXXXX        X',
  'm14': 'X        XXXXXXXXXXXXXXX        X',
  'm15': 'X        XXXXXXXXXXXXXXX        X',
  'm16': 'X        XXXXXXXXXXXXXXX        X',
  'm17': 'X        XXXXXXXXXXXXXXX        X',
  'm18': 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
  'm19': 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
  'n00': 'XXXXXXXXXXXXXXXXXXXXXXXXXX',
  'n01': 'XXXXXXXXXXXXXXXXXXXXXXXXXX',
  'n02': 'X        XXXXXXXX        X',
  'n03': 'X         XXXXXXX        X',
  'n04': 'X          XXXXXX        X',
  'n05': 'X           XXXXX        X',
  'n06': 'X            XXXX        X',
  'n07': 'X             XXX        X',
  'n08': 'X              XX        X',
  'n09': 'X        X      X        X',
  'n10': 'X        XX              X',
  'n11': 'X        XXX             X',
  'n12': 'X        XXXX            X',
  'n13': 'X        XXXXX           X',
  'n14': 'X        XXXXXX          X',
  'n15': 'X        XXXXXXX         X',
  'n16': 'X        XXXXXXXX        X',
  'n17': 'X        XXXXXXXXX       X',
  'n18': 'XXXXXXXXXXXXXXXXXXXXXXXXXX',
  'n19': 'XXXXXXXXXXXXXXXXXXXXXXXXXX',
  'o00': 'XXXXXXXXXXXXXXXXXXXXX',
  'o01': 'XXXXXXXXXXXXXXXXXXXXX',
  'o02': 'XXXXXX         XXXXXX',
  'o03': 'XXXX             XXXX',
  'o04': 'XX                 XX',
  'o05': 'X                   X',
  'o06': 'X        XXX        X',
  'o07': 'X       XXXXX       X',
  'o08': 'X       XXXXX       X',
  'o09': 'X       XXXXX       X',
  'o10': 'X       XXXXX       X',
  'o11': 'X       XXXXX       X',
  'o12': 'X       XXXXX       X',
  'o13': 'X        XXX        X',
  'o14': 'X                   X',
  'o15': 'XX                 XX',
  'o16': 'XXXX             XXXX',
  'o17': 'XXXXXX         XXXXXX',
  'o18': 'XXXXXXXXXXXXXXXXXXXXX',
  'o19': 'XXXXXXXXXXXXXXXXXXXXX',
  'p00': 'XXXXXXXXXXXXXXXXXXXXXX',
  'p01': 'XXXXXXXXXXXXXXXXXXXXXX',
  'p02': 'X                 XXXX',
  'p03': 'X                  XXX',
  'p04': 'X                   XX',
  'p05': 'X        XXXXX       X',
  'p06': 'XXX      XXXXX       X',
  'p07': 'XXX      XXXXX       X',
  'p08': 'XXX                 XX',
  'p09': 'XXX                XXX',
  'p10': 'XXX              XXXXX',
  'p11': 'XXX      XXXXXXXXXXXXX',
  'p12': 'XXX      XXXXXXXXXXXXX',
  'p13': 'XXX      XXXXXXXXXXXXX',
  'p14': 'X          XXXXXXXXXXX',
  'p15': 'X          XXXXXXXXXXX',
  'p16': 'X          XXXXXXXXXXX',
  'p17': 'X          XXXXXXXXXXX',
  'p18': 'XXXXXXXXXXXXXXXXXXXXXX',
  'p19': 'XXXXXXXXXXXXXXXXXXXXXX',
  'q00': 'XXXXXXXXXXXXXXXXXXXXX',
  'q01': 'XXXXXXXXXXXXXXXXXXXXX',
  'q02': 'XXXXXX         XXXXXX',
  'q03': 'XXXX             XXXX',
  'q04': 'XX                 XX',
  'q05': 'X                   X',
  'q06': 'X        XXX        X',
  'q07': 'X       XXXXX       X',
  'q08': 'X       XXXXX       X',
  'q09': 'X       XXXXX       X',
  'q10': 'X       XXXXX       X',
  'q11': 'X       XXXXX       X',
  'q12': 'X       XX  X       X',
  'q13': 'X        XX         X',
  'q14': 'X                   X',
  'q15': 'XX                 XX',
  'q16': 'XXXX              XXX',
  'q17': 'XXXXXX         X  XXX',
  'q18': 'XXXXXXXXXXXXXXXXX  XX',
  'q19': 'XXXXXXXXXXXXXXXXXXXXX',
  'r00': 'XXXXXXXXXXXXXXXXXXXXXX',
  'r01': 'XXXXXXXXXXXXXXXXXXXXXX',
  'r02': 'X                 XXXX',
  'r03': 'X                  XXX',
  'r04': 'X                   XX',
  'r05': 'X        XXXXX       X',
  'r06': 'XXX      XXXXX       X',
  'r07': 'XXX      XXXXX       X',
  'r08': 'XXX                 XX',
  'r09': 'XXX                XXX',
  'r10': 'XXX                 XX',
  'r11': 'XXX      XXXXX       X',
  'r12': 'XXX      XXXXX       X',
  'r13': 'XXX      XXXXX       X',
  'r14': 'X        XXXXX       X',
  'r15': 'X        XXXXX       X',
  'r16': 'X        XXXXX       X',
  'r17': 'X        XXXXX       X',
  'r18': 'XXXXXXXXXXXXXXXXXXXXXX',
  'r19': 'XXXXXXXXXXXXXXXXXXXXXX',
  's00': 'XXXXXXXXXXXXXXXXXXXXX',
  's01': 'XXXXXXXXXXXXXXXXXXXXX',
  's02': 'XXXX               XX',
  's03': 'XX                  X',
  's04': 'X                   X',
  's05': 'X       XXXXX       X',
  's06': 'X       XXXXXXXXXXXXX',
  's07': 'X       XXXXXXXXXXXXX',
  's08': 'XX         XXXXXXXXXX',
  's09': 'XXX             XXXXX',
  's10': 'XXXXX             XXX',
  's11': 'XXXXXXXX           XX',
  's12': 'XXXXXXXXXXXXX       X',
  's13': 'XXXXXXXXXXXXX       X',
  's14': 'X       XXXXX       X',
  's15': 'X                   X',
  's16': 'X                  XX',
  's17': 'XX               XXXX',
  's18': 'XXXXXXXXXXXXXXXXXXXXX',
  's19': 'XXXXXXXXXXXXXXXXXXXXX',
  't00': 'XXXXXXXXXXXXXXXXXXXXXXXXX',
  't01': 'XXXXXXXXXXXXXXXXXXXXXXXXX',
  't02': 'X                       X',
  't03': 'X                       X',
  't04': 'X                       X',
  't05': 'X                       X',
  't06': 'X      XX       XX      X',
  't07': 'XXXXXXXXX       XXXXXXXXX',
  't08': 'XXXXXXXXX       XXXXXXXXX',
  't09': 'XXXXXXXXX       XXXXXXXXX',
  't10': 'XXXXXXXXX       XXXXXXXXX',
  't11': 'XXXXXXXXX       XXXXXXXXX',
  't12': 'XXXXXXXXX       XXXXXXXXX',
  't13': 'XXXXXXXXX       XXXXXXXXX',
  't14': 'XXXXXXX           XXXXXXX',
  't15': 'XXXXXXX           XXXXXXX',
  't16': 'XXXXXXX           XXXXXXX',
  't17': 'XXXXXXX           XXXXXXX',
  't18': 'XXXXXXXXXXXXXXXXXXXXXXXXX',
  't19': 'XXXXXXXXXXXXXXXXXXXXXXXXX',
  'u00': 'XXXXXXXXXXXXXXXXXXXXXXX',
  'u01': 'XXXXXXXXXXXXXXXXXXXXXXX',
  'u02': 'X        XXXXX        X',
  'u03': 'X        XXXXX        X',
  'u04': 'X        XXXXX        X',
  'u05': 'X        XXXXX        X',
  'u06': 'XX       XXXXX       XX',
  'u07': 'XX       XXXXX       XX',
  'u08': 'XX       XXXXX       XX',
  'u09': 'XX       XXXXX       XX',
  'u10': 'XX       XXXXX       XX',
  'u11': 'XX       XXXXX       XX',
  'u12': 'XX       XXXXX       XX',
  'u13': 'XX        XXX        XX',
  'u14': 'XX                   XX',
  'u15': 'XXX                 XXX',
  'u16': 'XXXXX             XXXXX',
  'u17': 'XXXXXXX         XXXXXXX',
  'u18': 'XXXXXXXXXXXXXXXXXXXXXXX',
  'u19': 'XXXXXXXXXXXXXXXXXXXXXXX',
  'v00': 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
  'v01': 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
  'v02': 'X        XXXXXXXXXXX        X',
  'v03': 'X        XXXXXXXXXXX        X',
  'v04': 'X        XXXXXXXXXXX        X',
  'v05': 'X        XXXXXXXXXXX        X',
  'v06': 'XX       XXXXXXXXXXX       XX',
  'v07': 'XXX       XXXXXXXXX       XXX',
  'v08': 'XXXX       XXXXXXX       XXXX',
  'v09': 'XXXXX       XXXXX       XXXXX',
  'v10': 'XXXXXX       XXX       XXXXXX',
  'v11': 'XXXXXXX       X       XXXXXXX',
  'v12': 'XXXXXXXX             XXXXXXXX',
  'v13': 'XXXXXXXXX           XXXXXXXXX',
  'v14': 'XXXXXXXXXX         XXXXXXXXXX',
  'v15': 'XXXXXXXXXXX       XXXXXXXXXXX',
  'v16': 'XXXXXXXXXXXX     XXXXXXXXXXXX',
  'v17': 'XXXXXXXXXXXXX   XXXXXXXXXXXXX',
  'v18': 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
  'v19': 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
  'w00': 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
  'w01': 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
  'w02': 'X        XXXXXXXXXXXXXXXXXXXXXXXXXXX        X',
  'w03': 'X        XXXXXXXXXXXXXXXXXXXXXXXXXXX        X',
  'w04': 'X        XXXXXXXXXXXXXXXXXXXXXXXXXXX        X',
  'w05': 'X        XXXXXXXXXXXXXXXXXXXXXXXXXXX        X',
  'w06': 'XX       XXXXXXXXXXX     XXXXXXXXXXX       XX',
  'w07': 'XXX       XXXXXXXXX       XXXXXXXXX       XXX',
  'w08': 'XXXX       XXXXXXX         XXXXXXX       XXXX',
  'w09': 'XXXXX       XXXXX           XXXXX       XXXXX',
  'w10': 'XXXXXX       XXX             XXX       XXXXXX',
  'w11': 'XXXXXXX       X       X       X       XXXXXXX',
  'w12': 'XXXXXXXX             XXX             XXXXXXXX',
  'w13': 'XXXXXXXXX           XXXXX           XXXXXXXXX',
  'w14': 'XXXXXXXXXX         XXXXXXX         XXXXXXXXXX',
  'w15': 'XXXXXXXXXXX       XXXXXXXXX       XXXXXXXXXXX',
  'w16': 'XXXXXXXXXXXX     XXXXXXXXXXX     XXXXXXXXXXXX',
  'w17': 'XXXXXXXXXXXXX   XXXXXXXXXXXXX   XXXXXXXXXXXXX',
  'w18': 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
  'w19': 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
  'x00': 'XXXXXXXXXXXXXXXXXXXXXXX',
  'x01': 'XXXXXXXXXXXXXXXXXXXXXXX',
  'x02': 'X       XXXXXXX       X',
  'x03': 'X       XXXXXXX       X',
  'x04': 'X       XXXXXXX       X',
  'x05': 'X        XXXXX        X',
  'x06': 'X         XXX         X',
  'x07': 'XXXX       X       XXXX',
  'x08': 'XXXXX             XXXXX',
  'x09': 'XXXXXX           XXXXXX',
  'x10': 'XXXXXX           XXXXXX',
  'x11': 'XXXXX             XXXXX',
  'x12': 'XXXX       X       XXXX',
  'x13': 'X         XXX         X',
  'x14': 'X        XXXXX        X',
  'x15': 'X       XXXXXXX       X',
  'x16': 'X       XXXXXXX       X',
  'x17': 'X       XXXXXXX       X',
  'x18': 'XXXXXXXXXXXXXXXXXXXXXXX',
  'x19': 'XXXXXXXXXXXXXXXXXXXXXXX',
  'y00': 'XXXXXXXXXXXXXXXXXXXXXXX',
  'y01': 'XXXXXXXXXXXXXXXXXXXXXXX',
  'y02': 'X       XXXXXXX       X',
  'y03': 'X       XXXXXXX       X',
  'y04': 'X       XXXXXXX       X',
  'y05': 'X        XXXXX        X',
  'y06': 'X         XXX         X',
  'y07': 'XXXX       X       XXXX',
  'y08': 'XXXXX             XXXXX',
  'y09': 'XXXXXX           XXXXXX',
  'y10': 'XXXXXXX         XXXXXXX',
  'y11': 'XXXXXXXX       XXXXXXXX',
  'y12': 'XXXXXXXX       XXXXXXXX',
  'y13': 'XXXXXXXX       XXXXXXXX',
  'y14': 'XXXXXXXX       XXXXXXXX',
  'y15': 'XXXXX             XXXXX',
  'y16': 'XXXXX             XXXXX',
  'y17': 'XXXXX             XXXXX',
  'y18': 'XXXXXXXXXXXXXXXXXXXXXXX',
  'y19': 'XXXXXXXXXXXXXXXXXXXXXXX',
  'z00': 'XXXXXXXXXXXXXXXXXXXXX',
  'z01': 'XXXXXXXXXXXXXXXXXXXXX',
  'z02': 'X                   X',
  'z03': 'X                   X',
  'z04': 'X                   X',
  'z05': 'X                  XX',
  'z06': 'X     XXXXX       XXX',
  'z07': 'XXXXXXXXX       XXXXX',
  'z08': 'XXXXXXXX       XXXXXX',
  'z09': 'XXXXXXX       XXXXXXX',
  'z10': 'XXXXXX       XXXXXXXX',
  'z11': 'XXXXX       XXXXXXXXX',
  'z12': 'XXXX       XXXXXXXXXX',
  'z13': 'X         XXXXX     X',
  'z14': 'X                   X',
  'z15': 'X                   X',
  'z16': 'X                   X',
  'z17': 'X                   X',
  'z18': 'XXXXXXXXXXXXXXXXXXXXX',
  'z19': 'XXXXXXXXXXXXXXXXXXXXX',
}

runk = 0
result = {}
last_name = ''

for key in my_dict:
    temp1 = []
    name = str(key[0])
    if name != last_name:
        new_name = True
        temp2 = []
    last_name = name
    result[name] = []
    runk += 1
    runc = 0
    # print(my_dict[key])
    new_char = False
    last_char = ''
    for char in my_dict[key]:
        runc += 1
        if char != last_char:
            new_char = True
            temp1.append(1)
        else:
            new_char = False
            temp1[-1] += 1
        last_char = char
    #     print(name, runk, '-', runc, char, new_char, temp1)
    # print('temp1')
    # print(temp1)
    temp2.append(temp1)
    result[name] = temp2

print(result)

# for key, value in result.items():
#     print(key, len(value), value)















